export const tableData = [
    {
      Magna: '23/08/30',
      Ultrices: 'Consectetur',
      Ornare: 'Vestibulum',
      Erat: 'Egestas',
      Nisi: '154.181',
      Facilisis: '3',
      Elit: 'N/A',
      Senectus: 'Pretium',
      Felis: 'Turkey',
      Cursus: 'Nulla',
      Gravity: 'N/A',
      Rating: 1,
    },
    {
      Magna: '14/08/70',
      Ultrices: 'Consectetur',
      Ornare: 'Vestibulum',
      Erat: 'Egestas',
      Nisi: '154.181',
      Facilisis: '1',
      Elit: 'N/A',
      Senectus: 'Pretium',
      Felis: 'Australia',
      Cursus: 'Nulla',
      Gravity: 'N/A',
      Rating: 2,
    },
    {
      Magna: '11/06/55',
      Ultrices: 'Consectetur',
      Ornare: 'Vestibulum',
      Erat: 'Egestas',
      Nisi: '154.181',
      Facilisis: '5',
      Elit: 'N/A',
      Senectus: 'Pretium',
      Felis: 'India',
      Cursus: 'Nulla',
      Gravity: 'N/A',
      Rating: 3,
    },
    {
      Magna: '22/09/20',
      Ultrices: 'Consectetur',
      Ornare: 'Vestibulum',
      Erat: 'Egestas',
      Nisi: '154.181',
      Facilisis: '51',
      Elit: 'N/A',
      Senectus: 'Pretium',
      Felis: 'Nigeria',
      Cursus: 'Nulla',
      Gravity: 'N/A',
      Rating: 4,
    },
    {
      Magna: '22/09/20',
      Ultrices: 'Consectetur',
      Ornare: 'Vestibulum',
      Erat: 'Egestas',
      Nisi: '154.181',
      Facilisis: '32',
      Elit: 'N/A',
      Senectus: 'Pretium',
      Felis: 'Switzerland',
      Cursus: 'Nulla',
      Gravity: 'N/A',
      Rating: 5,
    }
  ];